### ISSUE TITLE
[1.12.2] Player clipping through the moving elevator (built from platforms)

### ISSUE THREAD

**Issue by iarspider** [BetterWithMods/BetterWithMods#733] opened 2018-01-13 20:33 UTC
If the player isn't looking straight forward while riding an elevator (3x3, 4 tall hollow box), there is high chance he will clip through the top of the box.

Forge 2560,
BetterWithMods 2.0.24

**Comment by iarspider** [comment] 2018-01-14 11:33
Even with the flat platform if the player is not looking straight the movement of the player on that platform will not be smooth.

**Comment by therealfarfetchd** [comment] 2018-01-20 08:51
I can't reproduce this, but I have an idea on how to fix this stuff once and for all.

**Comment by primetoxinz** [comment] 2018-01-22 16:13
Is this on a server or just single player?

**Comment by therealfarfetchd** [comment] 2018-01-22 17:32
The platform movement is definitely not influenced by the direction the player looks in. Do you have any other mods installed or only BWM?

**Comment by primetoxinz** [comment] 2018-03-19 22:13
Going to close this unless someone can reproduce or give more information

**Closed by primetoxinz** 2018-03-19 22:13 UTC
Labels: bug, enhancement
