### ISSUE TITLE
Exception loading model/blockstates

### ISSUE THREAD

**Issue by mankra** [BetterWithMods/BetterWithMods#683] opened 2017-12-03 10:36 UTC
https://pastebin.com/XPibyR4k

> Caused by: java.io.FileNotFoundException: betterwithmods:blockstates/multiblock_dummy.json

It is an issue. There are error messages in the log caused by your mod. There are ways to prevent these error messages.

Any software bloating the log file with untreated errors is bad software, no matter wether it's working or not.

You can make it better.

Solutions so far:

> He could simply add an empty json and the error should be away.

> If it does not need one, set the block to have no model like vanilla barriers do (It's one of the methods on Block)

**Comment by DaedalusGame** [comment] 2017-12-03 15:06
duplicate of #669 
please discuss there, and not in duplicate issues

**Closed by DaedalusGame** 2017-12-03 15:06 UTC
