### ISSUE TITLE
Soul Steel Anvil GUI Not Opening

### ISSUE THREAD

**Issue by TechnoMysterio** [BetterWithMods/BetterWithMods#696] opened 2017-12-16 22:35 UTC
Exactly what it says on the tin- uh, title. When I try to use the soul steel anvil by right-clicking on it, nothing happens. Something to do with HCDeadweight perhaps?

**Comment by primetoxinz** [comment] 2017-12-16 22:38
Can you give me your fml-latest.log right after attempting to open the anvil? 
HCDeadweight should have no effect and I cannot reproduce it in dev enviornment.

**Comment by TechnoMysterio** [comment] 2017-12-16 22:56
If you mean "lastest.log", then it seems that when I right-click the anvil, this pops up:

> java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
> 	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
> 	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
> Caused by: java.lang.ArrayIndexOutOfBoundsException

When I spam right-click the anvil, that message stacks up like crazy. Do ask if you need the whole log.

**Comment by primetoxinz** [comment] 2017-12-16 22:57
Please give me the entire file not just a snippet

**Comment by TechnoMysterio** [comment] 2017-12-16 22:59
Right right, I put it up on pastebin:

https://pastebin.com/s17xDsjd

**Comment by primetoxinz** [comment] 2017-12-21 18:51
Sorry for the wait, Couldn't reproduce this so I suggest removing some mods and trying until it works

**Comment by TechnoMysterio** [comment] 2017-12-21 21:56
Well, after taking all the mods out and putting them back in one-by-one, I found the culprit: OpenBlocks. The library mod OpenModsLib is fine, but as soon as I install OpenBlocks the Soul Steel Anvil stops working.

**Comment by primetoxinz** [comment] 2018-01-20 03:03
Fixed in OpenBlocks

**Closed** 2018-01-20 03:03 UTC
